# Generated by Django 5.2.6 on 2025-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(related_name='parents', to='students.student'),
        ),
    ]
